unbind d
unbind '"'
unbind %
bind r source-file ~/.tmux.conf
set -g prefix C-space
unbind-key C-b
bind C-space send-prefix
set -g status-interval 1
set -sg escape-time 0
set -g mouse on
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind q detach-client
bind X kill-session
bind - split-window -v
bind "|" split-window -h
set-option -g status-position top
set -g status-style 'bg=terminal'
set-option -g set-clipboard on

# Tmux Plugin-Manager
set -g @plugin 'tmux-plugins/tpm'
# Floatx
set -g @plugin 'omerxx/tmux-floax'
# M- means "hold Meta/Alt"
set -g @floax-bind '-n M-t'

# ─── Native Terminal Theme (Replaces Catppuccin) ───
set -g status-style "bg=terminal,fg=terminal"

# window style
set -wg automatic-rename on
set -g automatic-rename-format ''
set -g window-status-separator ' #[fg=brightblack]│#[default] '
set -g status-justify 'absolute-centre'

set -g window-status-format "#[fg=brightblack]#I:#{?#{!=:#{window_name},},#W,}"
set -g window-status-current-format "#[fg=magenta,bold]#I:#{?#{!=:#{window_name},},#W,}"

# status left style
set -g status-left-length 100
set -g status-left ""
# Highlights the session name in red when you hit your prefix key
set -ga status-left "#{?client_prefix,#[fg=red,bold] #S ,#[fg=green,bold] #S }"
set -ga status-left "#[fg=brightblack,none]│"
set -ga status-left "#[fg=yellow] #{pane_current_command} "

# status right style
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[fg=blue] #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-right "#[fg=brightblack,none]│"
set -ga status-right "#[fg=cyan] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
