color0 #171b24
color1 #facc6e
color2 #ed8274
color3 #87d96c
color4 #6dcbfa
color5 #dabafa
color6 #90e1c6
color7 #c7c7c7
color8 #686868
color9 #ffd173
color10 #f28779
color11 #d5ff80
color12 #73d0ff
color13 #dfbfff
color14 #95e6cb
color15 #ffffff

cursor                #ffcc66
cursor_text_color     #1f2430
background            #1f2430
foreground            #d1d1c7
selection_foreground  #1f2430
selection_background  #409fff
active_border_color   #d95757
inactive_border_color #1e222a
url_color             #d95757

active_tab_foreground   #0b0e14
active_tab_background   #d95757
inactive_tab_foreground #8e959e
inactive_tab_background #1e222a
cursor_trail_color      #8e959e
