color0 #15131b
color1 #b87a87
color2 #7aa89f
color3 #c4b794
color4 #463d5c
color5 #7866a3
color6 #9b8bc1
color7 #bfb3db
color8 #24202c
color9 #cf939f
color10 #91bfb6
color11 #ded4b6
color12 #5d507c
color13 #9b8bc1
color14 #bfb3db
color15 #efeef1

cursor                #9b8bc1
cursor_text_color     #15131b
background            #15131b
foreground            #bfb3db
selection_foreground  #15131b
selection_background  #24202c
active_border_color   #9b8bc1
inactive_border_color #24202c
url_color             #9b8bc1

active_tab_foreground   #15131b
active_tab_background   #9b8bc1
inactive_tab_foreground #bfb3db
inactive_tab_background #24202c
cursor_trail_color      #bfb3db
