color0 #26211e
color1 #e37874
color2 #a2b574
color3 #dfb26c
color4 #e09260
color5 #cca1b2
color6 #92bfa6
color7 #e6dfd3
color8 #453a35
color9 #eba19e
color10 #bcd492
color11 #f7cca1
color12 #f5b085
color13 #dec0cb
color14 #b5ded5
color15 #f7f3eb

cursor                #e6dfd3
cursor_text_color     #26211e
background            #161311
foreground            #e6dfd3
selection_foreground  #161311
selection_background  #a2b574
active_border_color   #a2b574
inactive_border_color #26211e
url_color             #a2b574

active_tab_foreground   #161311
active_tab_background   #a2b574
inactive_tab_foreground #c4b4a1
inactive_tab_background #26211e
cursor_trail_color      #c4b4a1
