# : Manager [[[

[mgr]
cwd = { fg = "#eedfe3" }

# Tab
tab_active = { fg = "#521d3c", bg = "#fcb0d6", bold = true }
tab_inactive = { fg = "#ffd8e9", bg = "#380726" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff9763", bg = "#ff9763" }
marker_cut = { fg = "#ffdbc9", bg = "#ffdbc9" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f3ba9b", bg = "#f3ba9b" }

# Count
count_copied = { fg = "#311302", bg = "#ffdbc9" }
count_cut = { fg = "#311302", bg = "#ffdbc9" }
count_selected = { fg = "#521d3c", bg = "#f3ba9b" }

# Border
border_symbol = "│"
border_style  = { fg = "#fcb0d6" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#521d3c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#fcb0d6", fg = "#521d3c", bold = true }
normal_alt  = { bg = "#504349", fg = "#d4c2c8" }

# Select mode
select_main = { bg = "#dfbdcc", fg = "#402a35", bold = true }
select_alt  = { bg = "#504349", fg = "#d4c2c8" }

# Unset mode
unset_main = { bg = "#f3ba9b", fg = "#4a2811", bold = true }
unset_alt  = { bg = "#504349", fg = "#d4c2c8" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#fcb0d6", bg = "#40373a" }
progress_error = { fg = "#ffb4ab", bg = "#40373a" }

# Permissions
permissions_t = { fg = "#ad567c" }
permissions_w = { fg = "#db5e1a" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff7530" }
permissions_s = { fg = "#ff3f93" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#fcb0d6" }
active = { fg = "#f3ba9b", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#fcb0d6" }
value = { fg = "#eedfe3" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#fcb0d6", bg = "#521d3c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#fcb0d6" }
title = {}
hovered = { fg = "#ffdbc9", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#40373a" }
cand = { fg = "#fcb0d6" }
rest = { fg = "#521d3c" }
desc = { fg = "#eedfe3" }
separator = " ▶ "
separator_style = { fg = "#eedfe3" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eedfe3" }
run = { fg = "#eedfe3" }
footer = { fg = "#402a35", bg = "#dfbdcc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f3ba9b" }
title_warn = { fg = "#fcb0d6" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#eedfe3" },
    { name = "*/", fg = "#fcb0d6" },
]

# : ]]]