general.import = ["colors.toml"]

general.live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 0.75 
dynamic_padding = true

[window.padding]
x = 15
y = 15

[font]
normal = { family = "FiraCode Nerd Font Mono"}
size = 14.0
offset = { x=0, y=0 }

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3
[env]
TERM = "xterm-256color"
[bell]
animation = "Linear"
duration = 0
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }
