[colors.primary]
background = '#181114'
foreground = '#eedfe3'
 
[colors.cursor]
text = '#eedfe3'
cursor = '#d4c2c8' 
 
[colors.vi_mode_cursor]
text = '#181114'
cursor = '#fcb0d5' 
 
[colors.search.matches]
foreground = '#504349' 
background = '#f3bb9a' 
 
[colors.search.focused_match]
foreground = '#504349' 
background = '#fcb0d5' 
 
[colors.footer_bar]
foreground = '#504349' 
background = '#eedfe3' 
 
[colors.hints.start]
foreground = '#504349' 
background = '#e0bdcc' 
 
[colors.hints.end]
foreground = '#504349' 
background = '#e0bdcc' 
 
[colors.selection]
text = '#181114'
background = '#fcb0d5'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#fcb0d5' 
yellow = '#884b6b' 
blue = '#fcb0d5' 
magenta = '#f3bb9a' 
cyan = '#e0bdcc' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
