# =============================================================================
# 1. CORE SHELL & INTERFACE THEME & PLUGINS	
# =============================================================================

[shell]
avatar_path = "/home/sumit/Pictures/avtar.jpg"
clipboard_history_max_entries = 20
font_family = "Monolisa"
password_style = "random"
settings_show_advanced = true
telemetry_enabled = false
time_format = "{:%H:%M %a}"
polkit_agent = true

[shell.panel]
launcher_categories = false
launcher_compact = true
transparency_mode = "glass"
control_center_placement = "floating"

[[shell.session.actions]]
action = "shutdown"
enabled = true
shortcut = "1"
variant = "destructive"

[[shell.session.actions]]
action = "reboot"
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "logout"
enabled = true
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "lock"
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "suspend"
enabled = true
shortcut = "5"
variant = "default"

[theme]
community_palette = "Monochrome"
source = "community"

[theme.templates]
builtin_ids = [
  "btop",
  "cava",
  "gtk3",
  "gtk4",
  "kitty",
  "niri",
  "qt",
  "starship",
  "wezterm",
]
community_ids = ["neovim", "obsidian", "vscode", "zed", "papirus-icons", "yazi"]

[wallpaper]
directory = "~/Pictures/Wallpapers"

[wallpaper.automation]
order = "alphabetical"

[wallpaper.default]
path = "/home/sumit/Pictures/Wallpapers/darkMountain.png"

[wallpaper.last]
path = "/home/sumit/Pictures/Wallpapers/darkMountain.png"

[wallpaper.monitors.HDMI-A-1]
path = "/home/sumit/Pictures/Wallpapers/darkMountain.png"

[wallpaper.monitors.eDP-1]
path = "/home/sumit/Pictures/Wallpapers/darkMountain.png"

[[wallpaper.favorite]]
community_palette = "Monochrome"
palette_source = "community"
path = "/home/sumit/Pictures/Wallpapers/1387138.png"
theme_mode = "light"

[[wallpaper.favorite]]
community_palette = "Monochrome"
palette_source = "community"
path = "/home/sumit/Pictures/Wallpapers/darkMountain.png"
theme_mode = "dark"

[plugins]
enabled = ["noctalia/bongocat"]

# =============================================================================
# 2. PANEL BAR & PANEL WIDGETS
# =============================================================================

[bar]
order = ["default"]

[bar.default]
background_opacity = 0.0
font_family = "MonoLisa"
capsule_border = ""
capsule_padding = 7.0
padding = 5
radius = 0
radius_top_left = 0
radius_top_right = 0
radius_bottom_left = 0
radius_bottom_right = 0
font_weight = 700
margin_ends = 0
shadow = false
thickness = 25
scale = 0.90
widget_spacing = 10
end = ["group:g4", "group:g2"]
margin_edge = 0
start = ["group:g1", "group:g3"]

[[bar.default.capsule_group]]
border = ""
fill = "surface_variant"
id = "g1"
members = ["launcher", "workspaces"]
opacity = 1.0
padding = 11.0

[[bar.default.capsule_group]]
border = ""
fill = "surface_variant"
id = "g2"
members = ["tray", "cat", "battery", "notifications"]
opacity = 1.0
padding = 7.0

[[bar.default.capsule_group]]
border = ""
fill = "surface_variant"
id = "g3"
members = ["temp", "cpu"]
opacity = 1.0
padding = 7.0

[[bar.default.capsule_group]]
border = ""
fill = "surface_variant"
id = "g4"
members = ["network", "bluetooth", "volume"]
opacity = 1.0
padding = 7.0

[widget.cat]
audio_spectrum = true
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.cpu]
display = "text"
show_label = false

[widget.temp]
display = "text"
show_label = false

[widget.tray]
drawer = true

[widget.clock]
capsule = true
format = "{:%-I:%M %p | %d %a}"

[widget.launcher]
glyph = "radioactive"

[widget.media]
min_length = 150

[widget.network]
show_label = false

[widget.notifications]
color = "primary"

[widget.spacer_2]
type = "spacer"

# =============================================================================
# 3. DESKTOP & LOCKSCREEN WIDGETS
# =============================================================================

[desktop_widgets]
enabled = false
schema_version = 1
widget_order = []

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true
[lockscreen_widgets]
enabled = false

# =============================================================================
# 4. HARDWARE, ENVIRONMENT, & INPUT CONTROLS
# =============================================================================

[brightness]
enable_ddcutil = true

[control_center]
sidebar_section = "full"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "session"

[idle]
behavior_order = ["lock", "screen-off", "lock-and-suspend"]

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 300

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = true
timeout = 900

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 330

[keybinds]
cancel = ["Escape"]
down = ["Ctrl+j"]
left = ["Ctrl+l"]
right = ["Ctrl+h"]
up = ["Ctrl+k"]
validate = ["Return"]

[location]
address = "chitwan,Nepal"

[nightlight]
enabled = true

[notification]
position = "bottom_right"

[osd]
position = "bottom_right"
