[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-eDPclock", "desktop-widget-eDPweather", "desktop-widget-HDMIclock", "desktop-widget-HDMIweather" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-HDMIclock]
    box_height = 224.0
    box_width = 1072.0
    cx = 1024.0
    cy = 211.20001220703125
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-HDMIclock.settings]
        background = false
        center_text = true
        font_family = "Maple Mono"
        format = "{:%^A}"
        shadow = true

    [desktop_widgets.widget.desktop-widget-HDMIweather]
    box_height = 80.0
    box_width = 176.0
    cx = 1392.0
    cy = 331.20001220703125
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-HDMIweather.settings]
        background = false
        font_family = "Maple Mono"
        shadow = false
        show_forecast = false

    [desktop_widgets.widget.desktop-widget-eDPclock]
    box_height = 224.0
    box_width = 1072.0
    cx = 768.0
    cy = 176.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-eDPclock.settings]
        background = false
        center_text = true
        font_family = "Maple Mono"
        format = "{:%^A}"
        shadow = true

    [desktop_widgets.widget.desktop-widget-eDPweather]
    box_height = 80.0
    box_width = 176.0
    cx = 1044.0
    cy = 276.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-eDPweather.settings]
        background = false
        font_family = "Maple Mono"
        shadow = false
        show_forecast = false

