# =============================================================================
# PANEL BAR & PANEL WIDGETS
# =============================================================================
[bar]
order = ["mini"]

[bar.mini]
show_on_workspace_switch = true
position = "top"
background_opacity = 1.0
border_width = 0.0
font_weight = 600
capsule_border = ""
capsule_radius = 0.0
thickness = 30
padding = 12
margin_edge = 0
margin_ends = 0
margin_opposite_edge = 0
radius = 0
concave_edge_corners = false
shadow = false
scale = 1
widget_spacing = 10
start = ["group:g2", "bar", "hostname","temp", "bar", "tray"]
center = ["audio-vis"]
end = [
  "group:sys",
  "bar",
  "brightness",
  "bar",
  "volume",
  "bar",
  "network",
  "bar",
  "bluetooth",
  "bar",
  "clock",
]
