# =============================================================================
# PANEL BAR & PANEL WIDGETS
# =============================================================================
[bar]
order = ["mini"]

[bar.mini]
show_on_workspace_switch = true
position = "bottom"
background_opacity = 1.0
border_width = 0.0
font_weight = 900
capsule_border = ""
capsule_radius = 5.0
thickness = 20 
padding = 10
margin_edge = 0
margin_ends = 0
margin_opposite_edge = 0
radius = 0
concave_edge_corners = false
shadow = false
scale = 1
widget_spacing = 12
start = ["launcher", "workspaces"]
center = []
end = [
  "tray",
  "notifications",
  "temp",
  "ram",
  "battery",
  "network",
  "volume",
  "clock",
]
