# =============================================================================
# 1. CORE SHELL & INTERFACE THEME & PLUGINS	
# =============================================================================

[theme]
community_palette = "Shien"
source = "community"

[theme.templates]
builtin_ids = [
  "btop",
  "cava",
  "gtk3",
  "gtk4",
  "kitty",
  "niri",
  "starship",
  "wezterm",
]
community_ids = [
  "neovim",
  "obsidian",
  "vscode",
  "zed",
  "papirus-icons",
  "yazi",
  "zathura",
]

[wallpaper]
directory = "~/Pictures/Wallpapers"

[wallpaper.automation]
order = "alphabetical"

[wallpaper.default]
path = "/home/sumit/Pictures/Wallpapers/wallhaven_lmwglr.jpg"

[wallpaper.last]
path = "/home/sumit/Pictures/Wallpapers/wallhaven_lmwglr.jpg"

[wallpaper.monitors.HDMI-A-1]
path = "/home/sumit/Pictures/Wallpapers/wallhaven_lmwglr.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/sumit/Pictures/Wallpapers/wallhaven_lmwglr.jpg"

[[wallpaper.favorite]]
community_palette = "Monochrome"
palette_source = "community"
path = "/home/sumit/Pictures/Wallpapers/1387138.png"
theme_mode = "light"

[[wallpaper.favorite]]
community_palette = "Monochrome"
palette_source = "community"
path = "/home/sumit/Pictures/Wallpapers/darkMountain.png"
theme_mode = "dark"

[[wallpaper.favorite]]
community_palette = "Shien"
palette_source = "community"
path = "/home/sumit/Pictures/Wallpapers/wallhaven_lmwglr.jpg"
theme_mode = "dark"

[[wallpaper.favorite]]
community_palette = "Monochrome"
palette_source = "community"
path = "/home/sumit/Pictures/Wallpapers/1387138.png"
theme_mode = "light"
