# =============================================================================
# 1. CORE SHELL & INTERFACE THEME & PLUGINS	
# =============================================================================

[theme]
community_palette = "Monochrome"
source = "community"

[theme.templates]
builtin_ids = [
  "btop",
  "cava",
  "foot",
  "gtk3",
  "gtk4",
  "kitty",
  "niri",
  "qt",
  "starship",
]
community_ids = [
  "zen-browser",
  "neovim",
  "obsidian",
  "vscode",
  "zed",
  "fastfetch",
  "zathura",
  "papirus-icons",
  "bat",
  "fzf",
  "tmux",
  "yazi",
]

[plugins]
enabled = [
  "cleboost/zed-provider",
  "cleboost/jetbrains-provider",
  "nightwatch75/file-search",
]

[wallpaper.default]
path = "/home/sumit/Pictures/Wallpapers/monochrome-sword-mastery-backiee-HD.jpg"

[wallpaper.last]
path = "/home/sumit/Pictures/Wallpapers/monochrome-sword-mastery-backiee-HD.jpg"

[wallpaper.monitors.HDMI-A-1]
path = "/home/sumit/Pictures/Wallpapers/monochrome-sword-mastery-backiee-HD.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/sumit/Pictures/Wallpapers/monochrome-sword-mastery-backiee-HD.jpg"
