[widget.workspaces]
display = "id"
style = "focus_hint"

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.volume]
show_label = false

[widget.cpu]
display = "text"
show_label = false

[widget.temp]
display = "text"
show_label = false

[widget.ram]
display = "text"
show_label = false
stat = "ram_pct"

[widget.clock]
color = "primary"
format = "| {:%H:%M  %d:%a}"
tooltip_format = "{:%A, %B %d, %Y}"

[widget.launcher]
glyph = "pacman"
color = "primary"

[widget.media]
min_length = 150

[widget.network]
show_label = false

[widget.notifications]
color = "primary"

[widget.spacer_2]
type = "spacer"
