[[bar.mini.capsule_group]]
id = "g2"
members = ["workspaces", "colon", "active_window"]
fill = "primary"
enabled = true

[[bar.mini.capsule_group]]
id = "sys"
members = ["battery","cpu", "ram"]
fill = "surface"
enabled = true
collapsible = true
collapsed_by_default = false
collapse_icon = "▸"
expand_icon = "▾"

[widget.workspaces]
style = "minimal"
focused_color = "on_primary"
hide_when_empty = true
occupied_color = "on_surface"
show_icons = false

[widget.active_window]
display = "text_only"
color = "on_primary"
min_length = 80
max_length = 150

[widget.audio-vis]
type       = "audio_visualizer"
width      = 200
bands      = 16
centered   = true
show_when_idle = true
color_1 = "primary"
color_2 = "secondary"
[widget.audio-vis.actions]
left = "panel-toggle control-center media"
right = "media toggle"

[widget.temp]
type = "sysmon"
stat = "cpu_temp"
show_glyph = false
visualization = "none"
color = "on_surface"

[widget.cpu]
type = "sysmon"
stat = "cpu_pct"
show_glyph = true
visualization = "none"
color = "on_surface"

[widget.ram]
type = "sysmon"
stat = "ram_pct"
show_glyph = true
visualization = "none"
color = "on_surface"

[widget.brightness]
show_label = false

[widget.volume]
type = "volume"
show_label = false

[widget.bluetooth]
show_label = false

[widget.network]
show_label = false

[widget.clock]
color = "primary"
format = "{:%I:%M} "
tooltip_format = "{:%A, %B %d, %Y}"

[widget.hostname]
type = "text"
text = "MEOW"
color = "primary"

[widget.bar]
type = "text"
text = "|"
